### ISSUE TITLE
No Postgres support?

### ISSUE THREAD

**Issue by ekandreas** [namumakwembo/wirechat#15]
### Package Version

0.0.6

### Laravel Version

v11

### Livewire Version

v3.5

### PHP Version

PHP 8.3

### Tailwind CSS Version

v3.3

### Environment Information

Laravel Herd

### Problem description

Browsing to /chats generates a 500 database error.

### Expected behavior

See some chat?

### Steps to reproduce

Install and browse to /chats

### Relevant log output

```shell
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: bigint = character varying LINE 1: ...rom "wire_actions" where "wire_participants"."id" = "wire_ac... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (Connection: pgsql, SQL: select * from "wire_conversations" where exists (select * from "wire_participants" where "wire_conversations"."id" = "wire_participants"."conversation_id" and "participantable_id" = 1 and "participantable_type" = App\Models\User and "exited_at" is null and not exists (select * from "wire_actions" where "wire_participants"."id" = "wire_actions"."actionable_id" and "wire_actions"."actionable_type" = Namu\WireChat\Models\Participant and "type" = removed-by-admin)) and exists (select * from "wire_participants" where "wire_conversations"."id" = "wire_participants"."conversation_id" and "participantable_id" = 1 and (conversation_deleted_at IS NULL OR conversation_deleted_at < wire_conversations.updated_at) and "exited_at" is null and not exists (select * from "wire_actions" where "wire_participants"."id" = "wire_actions"."actionable_id" and "wire_actions"."actionable_type" = Namu\WireChat\Models\Participant and "type" = removed-by-admin)) and exists (select * from "wire_messages" where "wire_conversations"."id" = "wire_messages"."conversation_id" and not exists (select * from "wire_actions" where "wire_messages"."id" = "wire_actions"."actionable_id" and "wire_actions"."actionable_type" = Namu\WireChat\Models\Message and "actor_id" != 1 and "actor_type" = App\Models\User and "type" = delete)) order by "updated_at" desc limit 10 offset 0)
```

**Comment by ekandreas** [comment]
Perhaps use standard Eloquent queries to support different databases?
In this case psql not supported.
Why postgres? We use it to support AI functionality with both GIS and embeddings.

**Comment by namumakwembo** [comment]
Thank you for reporting this issue! I’ll look into it and work on adjusting the package to use standard Eloquent queries to ensure compatibility with multiple databases. I’ll address this right away!

**Comment by namumakwembo** [comment]
Hello!

I installed PostgreSQL and was able to replicate the error. It turns out that the issue was not with raw SQL but rather with PostgreSQL's strictness when comparing different types, particularly when trying to join fields with mixed types (e.g., string and integer). This is likely causing the issue with the `actor_id` and `actionable_id` columns in your database.

I had only tested Wirechat on MySQL and other SQLite databases, so this issue may not have appeared on those platforms.

### Temporary Solution:

To resolve this issue for now, please update the `actor_id` and `actionable_id` columns in the `actions` table migrations to `unsignedBigInteger`:

1. Open the migration file for the `actions` table.
2. Change the column definitions for `actor_id` and `actionable_id` to:

```php
$table->unsignedBigInteger('actor_id');
$table->unsignedBigInteger('actionable_id');
```

This change will allow PostgreSQL to handle the comparison properly.

Thank you for your patience while I work on a more permanent solution!

**Comment by ekandreas** [comment]
Thank you for the quick answer and nice workaround.
